extends:
  - airbnb-base
  - prettier

plugins:
  - prettier
  - eslint-comments
  - jsdoc

env:
  es6: true
  browser: true

rules:
  prettier/prettier:
    - error
    - printWidth: 100
      tabWidth: 2
      semi: true
      trailingComma: all
      bracketSpacing: true
      jsxBracketSameLine: false
      singleQuote: true

  require-jsdoc: [
    error,
    require: {
      FunctionDeclaration: true,
      MethodDefinition: true,
      ClassDeclaration: true,
      ArrowFunctionExpression: true,
      FunctionExpression: true
    }
  ]

  valid-jsdoc: [
    error,
    {
      prefer: {
        arg: param,
        argument: param,
        class: constructor,
        return: returns,
        virtual: abstract,
        augment: extends,
        memberOf: memberof
      },
      preferType: {
        Boolean: boolean,
        Number: number,
        object: Object,
        String: string,
        undefined: void,
        Symbol: symbol
      },
      requireReturn: false,
      requireReturnType: true,
      matchDescription: ".+"
    }
  ]

  no-plusplus: off
  func-names: off
  linebreak-style: [off]
  no-implicit-coercion: error
  padding-line-between-statements: [
      error,
      { blankLine: always, prev: [const, let, var], next: "*" },
      { blankLine: always, prev: "*", next: [const, let, var] },
      { blankLine: any,    prev: [const, let, var], next: [const, let, var] },
      { blankLine: always, prev: "*", next: return },
      { blankLine: always, prev: "*", next: [case, default] },
      { blankLine: always, prev: [const, let, var, block, block-like], next: [block, block-like] },
      { blankLine: always, prev: directive, next: "*" },
      { blankLine: any,    prev: directive, next: directive },
  ]

  import/no-named-as-default: off
  import/newline-after-import: error
  import/prefer-default-export: off
  import/no-default-export: error

  eslint-comments/disable-enable-pair: error
  eslint-comments/no-duplicate-disable: error
  eslint-comments/no-unlimited-disable: error
  eslint-comments/no-unused-disable: warn
  eslint-comments/no-unused-enable: warn

  jsdoc/check-tag-names: error
  jsdoc/check-types: error
  jsdoc/newline-after-description: error
  jsdoc/require-description-complete-sentence: error
  jsdoc/require-param-description: error
  jsdoc/require-param-name: error
  jsdoc/require-param-type: error
  jsdoc/require-returns-description: error
  jsdoc/require-returns-type: error

